### ISSUE TITLE
GitHub Permissions for TODO Group Repos

### ISSUE THREAD

**Issue by gtback** [todogroup/governance#106]
👋🏻 Hi!

We started talking about this at the Work Day today, but these are questions best answered by the Steering Committee. I think most of these can be set [here](https://github.com/organizations/todogroup/settings/member_privileges). I get a 404 error because I'm not an owner of the TODO Group org, but that matches what it is for other orgs I'm an owner of.

1. What should the "Base Permissions" be set to for all repos in the org? I'm guessing it's "Read" now, but could possibly be changed to "Write"? Are there repos that we don't want members to be able to push to (like `governance`, perhaps)? Or would [branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches) (requiring a review from someone in the @todogroup/steering-committee team or via [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)) be OK? If not, I think we'd need to create a team for "All Members" and give that team Write permissions on repos we want people to be able to edit.
2. Should anyone in the organization be able to create new repos ("Repository creation")? That seems to the be the current setting, and I think it's fine, but wanted to be explicit.
3. Should the ["Owners" of the org](https://github.com/orgs/todogroup/people?query=role%3Aowner) be all the Steering committee members, or does it make sense to keep these lists separate?
4. Are there other Teams that make sense to add to manage permissions? I generally think Team permissions (either for the whole organization via Base Permissions or via teams added to specific repos) are more scalable than adding people individually to repos.

(I don't mind helping out with some of these permission/maintenance issues, once things are decided.)

**Comment by DuaneOBrien** [comment]
Thanks for the issue @gtback 

Context for SC, I didn't think we should make any of these changes during Work Day without discussing in the SC.

**Comment by anajsana** [comment]
Thanks, @gtback! I'll add this topic for the upcoming SC meeting (Dec 13th)

**Comment by justaugustus** [comment]
I'll make some suggestions based on previous experiences with GitHub org management...


### Org-level

- Enforce 2FA
- Default to `read`
- Create process for requesting repo creation
  - Disable repo creation for non-org owners
- Add Steering members as org admins
- Create process for becoming an org admin
- Enable [Allstar](https://github.com/ossf/allstar) to report compliance with the following:
  - repo has branch protection
  - repo does not have checked-in binaries
  - repo does not have outside collaborators
  - repo has a SECURITY.md

### Repo permissions

- Create teams to administer repos:
  - `repo-name-admins`: has `admin` role
  - `repo-name-maintainers`: has `maintain` role
- Enable branch protection for all repos: https://github.com/todogroup/governance/issues/69
- Add [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) with newly-created repo teams
- Disable outside collaborators once they have been reflected in `repo-name-maintainers` or `repo-name-admins`

### Managing org membership

Use [`peribolos`](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos) to enforce org settings and allow adding org members via pull request.

Example:

```yaml
name: TODO Group
description: Org description
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
billing_email: admin@org.name
admins:
- admin1
- admin2
- admin3
- admin4
- admin5
members:
- member1
- member2
- member3
- bot1
- bot2
teams:
  bots:
    description: Bot service accounts
    maintainers:
    - bot1
    members:
    - bot2
    privacy: closed
  members:
    description: TODO Group members
    members:
    - member1
    - member2
    - member3
    privacy: closed
  steering-committee:
    description: Steering Committee members
    maintainers:
    - admin1
    - admin2
    - admin3
    - admin4
    - admin5
    privacy: closed
  repo1-admins:
    description: Admins for repo1
    members:
    - member1
    privacy: closed
  repo1-maintainers:
    description: Maintainers for repo1
    members:
    - member1
    - member2
    - member3
    privacy: closed
```

The Kubernetes Community manages multiple orgs with this tool --> https://github.com/kubernetes/org

I'm working on making this easier to use for non-Kubernetes orgs here: https://github.com/relengfam/peribolos/pull/9
